### ISSUE TITLE
I keep swaping between white and black backgrounds and no sprites in the junkyard

### ISSUE THREAD

**Issue by SpaceCowboy3514** [07th-mod/onikakushi#194] opened 2020-08-21 08:16 UTC
I have no idea what's happening because I doubt this is intentional https://cdn.discordapp.com/attachments/392489108875771906/746275878526517308/unknown.png

**Comment by drojf** [comment] 2023-02-02 09:55
I noticed you can reproduce this if you change a graphics preset before reaching the title screen, however it should only persist until the game is restarted - See https://github.com/07th-mod/higurashi-assembly/issues/104

I'm going to assume this is a duplicate of that issue (although I think this is the only user report we've had of this issue happening in the wild)

**Closed by drojf** 2023-02-02 09:55 UTC
