### ISSUE TITLE
Missing red light in Settings

### ISSUE THREAD

**Issue by mfdsrax2** [07th-mod/onikakushi#184] opened 2019-06-02 13:34 UTC
When choosing 'Remake' in 'Character Sprites' there is no red light in the background. I tried all options and this is the only one missing.

![20190602120839_1](https://user-images.githubusercontent.com/13324717/58762065-1ff47a00-857e-11e9-866e-28622494e425.jpg)
![Inked20190602120832_1_LI](https://user-images.githubusercontent.com/13324717/58762069-24209780-857e-11e9-8b2f-9cfe402b4cd7.jpg)

**Comment by enumag** [comment] 2019-06-02 13:36
Duplicate of https://github.com/07th-mod/meakashi/issues/31

**Comment by enumag** [comment] 2019-06-02 13:51
Actually let me close the other one and reopen this. This issue is a bit better reported.

**Comment by enumag** [comment] 2019-06-02 13:52
@tellowkrinkle could you look into this one as well some time? I think you're the only one on the team with a chance of fixing this.

**Comment by tellowkrinkle** [comment] 2019-06-02 13:55
Yeah I know the issue with the display sizes was that the game was comparing the screen width against hardcoded values that only worked for 4:3, it's probably something similar

**Closed** 2019-11-20 20:28 UTC
