### ISSUE TITLE
some voices not playing? troubleshooting didn't work.

### ISSUE THREAD

**Issue by samcambolt270** [07th-mod/onikakushi#69] opened 2016-10-10 19:02 UTC
so, heres what happened. I installed the mod, loaded my save, and it seemed to work. then, i wanted to start over, and test some of the earlier voices. i noticed at the point when keiichi's father wakes him up on the train, that his line wasnt voiced. i thought this might just be an isolated thing, and kept playing. later,  noticed his mom wasnt voiced either, and at the point when rena first shows up, she wasnt voiced either. so, i went to check the instructions for troublshooting and deleted the specified script files, started over again. this time, his father was voiced, but shortly afterward at the breakfast scene, again his mom and rena are not voiced, and after loading a few of my savegames, i found that they are not voiced for a good while, and then gain voices later. i am wonder if this is an issue with my installation? what should i do?
EDIT: i forgot to mention that im using voices only.

**Comment by ItaloKnox** [comment] 2016-10-10 19:30
Unfortunately for Onikakushi we don't support the voices only patch. :(
Maybe that's why you are having issues with the game.

At least I suggest you to reinstall the voice folders and see if it works. The voices and graphics patch covers all voices from the PS3 version, so you shouldn't have issues if the voice file actually exists. Maybe that's a problem only in the voices only patch.

**Comment by samcambolt270** [comment] 2016-10-10 19:31
ah. i guess i could try the full patch with graphics and see if that fixes it. thanks

**Comment by samcambolt270** [comment] 2016-10-10 21:58
new issue. i followed the instructions for the full installation, and it works fine if i dont overwrite the scripts. but the instant i overwrite the scripts, i get a black screen on boot.  even after removing and replacing the entire scripts folder with the original ones, i still get a black screen. the only fix seems to be a full reinstall...

**Comment by samcambolt270** [comment] 2016-10-10 22:10
any way to fix this?

**Comment by ItaloKnox** [comment] 2016-10-10 22:38
Try cleaning both ``CompiledScripts`` and ``CompiledUpdateScripts`` folders a couple of times. Sometimes the engines bugs and you have a lot of trouble setting it up again. Happened to me once. The game should hang in a black screen for a few seconds (maybe a minute at most) while it compiles the scripts.

Don't forget that you are supposed to have the patch scripts inside the ``Update`` folder, and you are not supposed to use the ``Update`` folder that comes with the **graphics** patch.

**Comment by samcambolt270** [comment] 2016-10-10 22:56
the update folder doesnt work for me. i need to actually replace the scripts for it to work.

**Comment by ItaloKnox** [comment] 2016-10-10 22:58
That's not how the patch is supposed to work. I think you need to reinstall and doublecheck your stuff, jumping through hoops to make the patch work won't fix your problem. In fact, there's absolutely no issues with the patch right now.

Can you tell me which version of the game are you running? Is it the Steam version?

**Comment by samcambolt270** [comment] 2016-10-10 23:03
mangagamer actually. i dont know about a version. i just know the update folder doesnt do anything at all. when i followed the voice only instructions, it said if the the update folder doesnt work, to replace the scripts in the scripts folder with the update folder.

**Comment by ItaloKnox** [comment] 2016-10-10 23:08
You are probably running an older version of the came. I suggest you to download it again from your MangaGamer account. If the Update folder doesn't do anything, that means the engine doesn't support half of the stuff added to support our patch.

Best thing I can suggest is to keep forcing your way into the scripts folder, but there's no guarantee it will work. There are currently no issues with our Onikakushi patch, so the problem is most likely on your end.

**Comment by samcambolt270** [comment] 2016-10-10 23:11
ok. I'll try that out when i get the chance.

**Comment by samcambolt270** [comment] 2016-10-11 01:23
redownloading fixed it. thanks for your help.

**Comment by ItaloKnox** [comment] 2016-10-11 02:26
Good to know, you can reopen this issue if you have any more problems.

**Closed by ItaloKnox** 2016-10-11 02:26 UTC
